common: &common
  adapter: postgresql
  username: ttt
  password: ttt
  host: localhost

development:
  <<: *common
  database: ttt_dev

test:
  <<: *common
  database: ttt_test

production:
  <<: *common
  database: ttt_prod
